// Auto-generated cross-language test vectors for lever-runner-wasm
// DO NOT EDIT — generated by validate_all.py from test-vectors.json

const testVectors = require("../superinstance-ecosystem/test-vectors.json");

const { blake3 } = require("blake3"); // or appropriate import

function hexToBytes(hex) {
    const bytes = new Uint8Array(hex.length / 2);
    for (let i = 0; i < hex.length; i += 2) {
        bytes[i / 2] = parseInt(hex.substr(i, 2), 16);
    }
    return bytes;
}

function float32ToHex(value) {
    const buf = new ArrayBuffer(4);
    new DataView(buf).setFloat32(0, value, true); // little-endian
    return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, "0")).join("");
}

async function runTests() {
    let pass = 0, fail = 0;
    const data = testVectors;
    const actions = data.actions;

    console.log("══════════════════════════════════════════════════");
    console.log("🌐 JS/WASM Validation (lever-runner-wasm)");
    console.log("══════════════════════════════════════════════════");

    // BLAKE3 hash tests
    for (const v of data.vectors) {
        const input = Buffer.from(v.state, "utf-8");
        const hash = blake3.hash(input).toString("hex").slice(0, 32); // 128-bit = 32 hex chars
        if (hash === v.expected_hash_hex) {
            pass++;
        } else {
            console.log(`FAIL ${v.id} hash: expected ${v.expected_hash_hex}, got ${hash}`);
            fail++;
        }
    }

    // Score encoding tests
    for (const v of data.vectors) {
        const hex = v.scores.map(s => float32ToHex(s)).join("");
        if (hex === v.score_bytes_hex) {
            pass++;
        } else {
            console.log(`FAIL ${v.id} scores: expected ${v.score_bytes_hex}, got ${hex}`);
            fail++;
        }
    }

    // Best action tests
    for (const v of data.vectors) {
        const max = Math.max(...v.scores);
        const count = v.scores.filter(s => s === max).length;
        if (v.best_action_index === -1) {
            if (count > 1) { pass++; }
            else { console.log(`FAIL ${v.id} best: expected tie`); fail++; }
        } else {
            const best = v.scores.indexOf(max);
            if (best === v.best_action_index) { pass++; }
            else { console.log(`FAIL ${v.id} best: expected ${v.best_action_index}, got ${best}`); fail++; }
        }
    }

    console.log(`  JS/WASM: ${pass} passed, ${fail} failed`);
    process.exit(fail > 0 ? 1 : 0);
}

runTests().catch(e => { console.error(e); process.exit(1); });
